services:
  logger:
    image: jpkitt/logger:latest
    ports:
      - 80:80
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
volumes:
  mongodb_data: